// <auto-generated />
using System;
using BRW.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BRW.Infrastructure.Migrations
{
    [DbContext(typeof(BrwContext))]
    [Migration("20220124170124_addGuidRandom")]
    partial class addGuidRandom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BRW.Domain.Entities.Championship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_championships");

                    b.ToTable("championships", (string)null);
                });

            modelBuilder.Entity("BRW.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_groups_team_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("BRW.Domain.Entities.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChampionshipId")
                        .HasColumnType("integer")
                        .HasColumnName("championship_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_prizes");

                    b.HasIndex("ChampionshipId")
                        .HasDatabaseName("ix_prizes_championship_id");

                    b.ToTable("prizes", (string)null);
                });

            modelBuilder.Entity("BRW.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChampionshipId")
                        .HasColumnType("integer")
                        .HasColumnName("championship_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("ChampionshipId")
                        .HasDatabaseName("ix_teams_championship_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_teams_group_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("BRW.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<char>("Role")
                        .HasColumnType("character(1)")
                        .HasColumnName("role");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_users_team_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BRW.Domain.Entities.Group", b =>
                {
                    b.HasOne("BRW.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BRW.Domain.Entities.Prize", b =>
                {
                    b.HasOne("BRW.Domain.Entities.Championship", null)
                        .WithMany("Prizes")
                        .HasForeignKey("ChampionshipId")
                        .HasConstraintName("fk_prizes_championships_championship_id");
                });

            modelBuilder.Entity("BRW.Domain.Entities.Team", b =>
                {
                    b.HasOne("BRW.Domain.Entities.Championship", null)
                        .WithMany("Teams")
                        .HasForeignKey("ChampionshipId")
                        .HasConstraintName("fk_teams_championships_championship_id");

                    b.HasOne("BRW.Domain.Entities.Group", null)
                        .WithMany("Teams")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("fk_teams_groups_group_id");
                });

            modelBuilder.Entity("BRW.Domain.Entities.User", b =>
                {
                    b.HasOne("BRW.Domain.Entities.Team", null)
                        .WithMany("Integrants")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("fk_users_teams_team_id");
                });

            modelBuilder.Entity("BRW.Domain.Entities.Championship", b =>
                {
                    b.Navigation("Prizes");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("BRW.Domain.Entities.Group", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("BRW.Domain.Entities.Team", b =>
                {
                    b.Navigation("Integrants");
                });
#pragma warning restore 612, 618
        }
    }
}
