version: '3'

services:
  Brw-app:
    container_name: brw-app
    image: brw-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1e4794496a58be1f176346173efae5421420aef3
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - postgres-Brw-database
  
  postgres-Brw-database:
    container_name: brw-database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "1e4794496a58be1f176346173efae5421420aef3"
    ports:
      - "5432:5432"
    volumes:
      - /home/brw-db/:/var/lib/postgresql/data

